language: ruby
rvm:
- 2.7
dist: bionic
cache:
  directories:
  - vendor/bundle/



env:
  global:
  - PACKAGE_VERSION=1.0.$TRAVIS_BUILD_NUMBER



before_install:
- gem install bundler
install:
- bundle install --standalone --clean --jobs=3 --retry=3



script:
- bundle exec rake build:release



deploy:
  provider: releases
  api_key:
    secure: ows7ysSATG0TXT4oEbxJPccf1x5twXoqMcyH7z244bFighPfrQi5UqOHo/52aeHAwuvbkHU4CQ9hd4DR26h2AEzJCK6rHypH/eOZnGsDQ/Mbfv4iMBpoJYzNnUisjaI72yUSl2/69eMY4RM0pcg7/EMkV8Vx0/mATvkrY2agFFBA3iGdrt6DhjZlNv4IYCzPnRlfiO1Q6CyqKLikGSKdPiITEu+HiWNd94jkNlxvlVyIupNLzurVKzVLQT5IbERBAqsDf55b9Av5ltqTiSbfF20OKDWPCHhbyhoZZ5aq0IkWfZtJI3bcgM93obh6l23HdcfFQeVrAkdsBHSJYD/P/8jNKqKzEhzMOpo6BFQANmnO1KHS4QDZNvMrTX11v+yntESy2JH+UasO1e+T8U7Ujxqg0YoeD2DieuaPni+E/Aq5kYP2+BTh2YXvOEiBI+vSIDvjtoknhjf6KkW7d0x0gVqa8ZtyvV8KYZQuVz5hZnCAXrnUukBSZJHAZ5l/Hr1d4LQM2Rx0VSOqTAToWEpKjIMiSDXR9gwRiw6oXrkgrMpJGoSkoFkE9C5v1sP9PMKgzpVZvZaj5TlAttpAucSnLNA0zXwgnbo+WDUwlJOoUDbLJg/MfhvsEDst7ornqYWCGuVy39GKMExmcFhojwTrarTyYeQM272CGG1u07k3GlY=
  file_glob: true
  file: tmp/out/bin/*
  skip_cleanup: true
  on:
    repo: mcartoixa/mcartoixa.github.io
    tags: true
