title: Mathieu Cartoixa
subtitle: Software Craftsman
#email: your-email@example.com
description: >-
  I am a Software Craftsman who loves music, photography and travels, amongst many other interests.
  This is my personal page, where I try and gather all my activities on the web, be they professional or personal.
author: mcartoixa
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mcartoixa.me" # the base hostname & protocol for your site, e.g. http://example.com
avatar: /assets/images/avatar.png

google_analytics: G-0BMMJFSH36
twitter:
  username: mcartoixa
  card: summary
social:
  name: Mathieu Cartoixa
  links:
    - https://twitter.com/mcartoixa
    - https://www.facebook.com/mathieu.cartoixa
    - https://www.linkedin.com/in/cartoixa/
    - https://github.com/mcartoixa

bitbucket_url: https://bitbucket.org/mcartoixa/
bluesky_url: https://bsky.app/profile/mcartoixa.me
dev_url: https://dev.to/mcartoixa
facebook_url: https://www.facebook.com/mathieu.cartoixa
github_url: https://github.com/mcartoixa
goodreads_url: https://www.goodreads.com/user/show/8699028-mathieu
instagram_url: https://www.instagram.com/mcartoixa/
lastfm_url: https://www.last.fm/user/cartoixa
linkedin_url: https://www.linkedin.com/in/cartoixa/
macsings_facebook_url: https://www.facebook.com/macsings
macsings_youtube_url: https://www.youtube.com/@macsings
reddit_url: https://www.reddit.com/user/mcartoixa
soundcloud_url: https://soundcloud.com/mcartoixa/
stackoverflow_url: https://stackoverflow.com/users/8696/mac
steam_url: https://steamcommunity.com/id/mcartoixa
threads_url: https://www.threads.net/@mcartoixa
twitter_url: https://twitter.com/mcartoixa
untappd_url: https://untappd.com/user/mcartoixa
xing_url: https://www.xing.com/profile/Mathieu_Cartoixa
youtube_url: https://www.youtube.com/user/cartoixa

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  # Default plugins (cf. https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins)
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-remote-theme
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # Other plugins
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


collections:
  sections:
    output: true
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/avatar.png
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
      image: /assets/images/nyc-mac.jpg

feed:
  path: atom.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - build/
  - build.sh
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - tmp/
  - vendor/
