version: '3.9'
services:
  mcartoixa-github-io:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    user: mcartoixa
    volumes:
      - workspace:/home/mcartoixa/src
      - ..:/home/mcartoixa/mnt
    volumes_from:
        - glue
    working_dir: /home/mcartoixa/src
    command: /bin/sh -c "while sleep 1000; do :; done"
  glue:
    image: alpine
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  workspace:
